"project_id": "380544"
"main_file_id": "11735"
"api_token": "_secret_"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  [
    {
      "source": "/msg_hash_us.json",
      "translation": "/msg_hash_%two_letters_code%.json",
    },
    {
      "source": "/steam_us.json",
      "translation": "/steam_%two_letters_code%.json",
    },
    {
      "source": "/googleplay_us.json",
      "translation": "/googleplay_%two_letters_code%.json",
    },
  ]
