name: CI Emscripten

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-emscripten:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3
    
    - name: Compile RA
      run: |
        emmake make -f Makefile.emscripten -j$(getconf _NPROCESSORS_ONLN) clean
        emmake make -f Makefile.emscripten -j$(getconf _NPROCESSORS_ONLN) HAVE_STATIC_DUMMY=1

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - uses: actions/upload-artifact@v4
      with:
        name: RA-Emscripten-dummy-${{ steps.slug.outputs.sha8 }}
        path: |
          retroarch.js
